### ISSUE TITLE
As a user, I want to see a cutting edge version of the API populated with significant datasets

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#178]
## 💪 Motivation
...so that I can see a demonstration of science use cases independantly from the availability of data in the production registries.

## 📖 Additional Details

Foreseen subtasks are:

- [ ]  deploy the new registry
- [ ] - populate it with OREX data
- [ ] - upgrade the jupyter notebook with latest python api-client

## ⚖️ Acceptance Criteria
**Given** the jupyter notebook on https://github.com/nasa-pds/pds-api-notebook and the deployed server
**When I perform** the notebooks proposed 
**Then I expect** I expect them to work and return significant results

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @jimmie alternativelly we can use the node registry and help them to ingest the data we need for a demo. If that is acceptable. The cost of running a new registry would be spared.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl per our conversation on the sprint review, I think we can just ingest these data sets into the operational ENG registry for now, and just make sure we document the LIDVIDs of the bundles/collections that are ingested so we can notify those nodes that we have ingested that data on the interim, and to let us know when they have done so and we will remove it from our registry.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams we don't have a registry on pdscloud-gamma (at least not the server side components) since the registry deployment is mostly independent from these web machines (only the cloud-front and load balancer are shared).

@jimmie has a development server but I don't think it has a public facing entry. i don't know if we could use this instance as our prod-demo. I don't feel like it is the same.

So I think loading in production servers make a better sense.

**Comment by jimmie** [comment]
@tloubrieu-jpl Yes, the development load balancer does not have a public endpoint (we ran out of DNS/certs). We could run the dev registry service through the public load balancer (and CloudFront) if you really want a publicly available demo system - it won't interfere with the production system, we would just need to add a rule to the prod load balancer.

**Comment by tloubrieu-jpl** [comment]
Thanks @jimmie I don't think we need that for now. What we need is closer to production status.

@jordanpadams should I ask @rchenatjpl to load the data in the new registry ? Or @c-suh ? I don't think @rchenatjpl works with the new registry yet.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl we should talk this over with @viviant100 and @rchenatjpl . This should start to become part of our every day operations
