### ISSUE TITLE
Support latest product search from API

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#230]
## 💡 Description

- [x] define the archive status
- [x] update harvest to use the right archive status
- [x] update registry-mgr to use the right status and new schema with history
- [x] integrate in registry, with test dataset and realistic harvest/registry-mgr workflow and provenance.py in a docker image
- [x] prepare deployment on AWS

deploy in production:
- [x] upgraded registry-api
- [x] provenance.py script

**Comment by jordanpadams** [comment]
awaiting completion of deployment:
https://github.com/NASA-PDS/registry/issues/140
https://github.com/NASA-PDS/registry/issues/141

**Comment by jordanpadams** [comment]
:calendar: December status: Delayed per deployment noted above

**Comment by jordanpadams** [comment]
📆 January status: Delayed a sprint as provenance script is being deployed and registries reindexed. no expected impact on delivery.

**Comment by jordanpadams** [comment]
Script deployed to Amazon Eventbridge Scheduler. TBD if we need a separate ticket for adding to integration tests, but will call this one good for now.
